<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzilEdu.Shared\AzilEdu.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\brid.webp" />
    <None Include="wwwroot\images\cat.jpg" />
    <None Include="wwwroot\images\dog.jpg" />
    <None Include="wwwroot\images\hamster.jpg" />
  </ItemGroup>

</Project>
